version: '3.8'
services:
  back:
    container_name: 'url-shortener-back'
    build:
      context: ${ROOT_PATH}
      dockerfile: back/Dockerfile
    env_file: .env
    working_dir: '/usr/src/back'
    restart: always
    ports:
      - 3003:3000
    volumes:
      - ${ROOT_PATH}/.env.example:/usr/src/.env.example
      - ${ROOT_PATH}/back/bin:/usr/src/back/bin
      - ${ROOT_PATH}/back/model:/usr/src/back/model
      - ${ROOT_PATH}/back/public:/usr/src/back/public
      - ${ROOT_PATH}/back/routes:/usr/src/back/routes
      - ${ROOT_PATH}/back/services:/usr/src/back/services
      - ${ROOT_PATH}/back/modules:/usr/src/back/modules
      - ${ROOT_PATH}/back/app.js:/usr/src/back/app.js
      - ${ROOT_PATH}/back/package.json:/usr/src/back/package.json
      - ${ROOT_PATH}/back/package-lock.json:/usr/src/back/package-lock.json
    logging:
      driver: json-file
    networks:
      - url_shortener_network
  front:
    container_name: 'url-shortener-front'
    build:
      context: ${ROOT_PATH}
      dockerfile: front/Dockerfile
    env_file: .env
    working_dir: '/usr/src/front'
    restart: always
    ports:
      - 3004:3000
    volumes:
      - ${ROOT_PATH}/.env.example:/usr/src/.env.example
      - ${ROOT_PATH}/front/pages:/usr/src/front/pages
      - ${ROOT_PATH}/front/public:/usr/src/front/public
      - ${ROOT_PATH}/front/styles:/usr/src/front/styles
      - ${ROOT_PATH}/front/modules:/usr/src/front/modules
      - ${ROOT_PATH}/front/next.config.js:/usr/src/front/next.config.js
      - ${ROOT_PATH}/front/package.json:/usr/src/front/package.json
      - ${ROOT_PATH}/front/yarn.lock:/usr/src/front/yarn.lock
    logging:
      driver: json-file
    networks:
      - url_shortener_network
  db:
    image: mysql:5.7
    container_name: ${DB__HOST}
    volumes:
      - ${ROOT_PATH}/database/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB__ROOT_PASSWORD}
      MYSQL_USER: ${DB__USER}
      MYSQL_PASSWORD: ${DB__PASSWORD}
      MYSQL_DATABASE: ${DB__NAME}
    logging:
      driver: json-file
    networks:
      - url_shortener_network

networks:
  url_shortener_network:
